# Generated by Django 4.2.2 on 2023-07-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255, null=True)),
                ("site_url", models.URLField(null=True)),
                ("location", models.CharField(max_length=255)),
                ("rating", models.FloatField(null=True)),
            ],
        ),
    ]
