# Generated by Django 4.2.3 on 2023-07-05 19:35

from django.core.management import call_command
from django.db import migrations


def func(apps, schema_editor):
    call_command("loaddata", "data_fixture.json")


class Migration(migrations.Migration):
    dependencies = [
        ("generator", "0001_initial"),
    ]

    operations = [migrations.RunPython(func)]
